language: go
sudo: false

os:
  - linux
  - osx
  - windows

env:
  - GO111MODULE=on

go:
  - 1.14.x

script:
  # Run tests
  - go test -race -v -bench=. -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then bash <(curl -s https://codecov.io/bash) ; fi

notifications:
  slack: performix:yXTihlSzsLFSZiqbXMNzvTSX
